name: PAYDO TJ Android APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-android:
    name: Build PAYDO TJ APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Check Flutter
        run: flutter --version

      - name: Create Android platform
        run: flutter create --platforms=android --overwrite .

      - name: Set application name
        run: |
          python3 - <<'PY'
          from pathlib import Path

          p = Path("android/app/src/main/AndroidManifest.xml")

          if p.exists():
              text = p.read_text()
              text = text.replace(
                  'android:label="${applicationName}"',
                  'android:label="PAYDO TJ"'
              )
              text = text.replace(
                  'android:label="paydo_tj"',
                  'android:label="PAYDO TJ"'
              )
              p.write_text(text)
          PY

      - name: Install dependencies
        run: flutter pub get

      - name: Generate Android icon
        run: dart run flutter_launcher_icons

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: PAYDO-TJ-APK
          path: build/app/outputs/flutter-apk/app-release.apk
          if-no-files-found: error
