name: PAYDO.TJ APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-apk:
    name: Build PAYDO.TJ APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Show Flutter version
        run: flutter --version

      - name: Recreate Android platform
        run: |
          flutter create \
            --platforms=android \
            --project-name=paydo_tj \
            --overwrite .

      - name: Get packages
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: PAYDO-TJ-APK
          path: build/app/outputs/flutter-apk/app-release.apk
          if-no-files-found: error
