name: Create Platform Files

on:
  workflow_dispatch:

jobs:
  create:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.0'
          channel: stable

      - name: Create Android iOS Windows files
        run: |
          flutter pub get
          flutter create . --platforms=android,ios,windows

      - name: Commit platform files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add android ios windows
          git diff --cached --quiet || git commit -m "Create Android iOS Windows platform files"
          git push
